# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Tools
      run: sudo apt-get update && sudo apt-get install -y
            ninja-build clang cppcheck clang-tidy clang-format
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.0'
        host: 'linux'
        dir: ${{env.BUILD_PATH}}
        aqtversion: '==3.1.*'
        target: 'desktop'
        arch: 'gcc_64'
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DCMAKE_CXX_COMPILER=clang++
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build -E Qml # without Qml test
    - name: cppcheck
      run: ninja -C build cppcheck-check
    - name: clang-tidy
      run: ninja -C build clang-tidy-check
    - name: clang-format
      run: ninja -C build clang-format-check

